In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/online_shoppers.csv")

In [3]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
df = data.drop_duplicates()
df.shape

(12205, 18)

In [5]:
y = df['Revenue']
X= df.drop(columns = 'Revenue')

In [6]:
from sklearn.model_selection import train_test_split

In [7]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify= y)

In [8]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9764, 17), (2441, 17), (9764,), (2441,))

In [9]:
y_train.mean()

np.float64(0.15628840639082342)

In [10]:
y_test.mean()

np.float64(0.15649324047521507)

## Split
total size after duplicated drop = (12205,18)
test rate = 0.2
Purchase rate: train 15.6%, test 15.6% (stratified)

In [11]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, recall_score

In [12]:
dummy = DummyClassifier(strategy = 'most_frequent')
dummy.fit(X_train,y_train)
predictions = dummy.predict(X_train)

print(f" Accuracy : {accuracy_score(y_train, predictions):.3f} \n Recall : {recall_score(y_train,predictions)}")

 Accuracy : 0.844
 Recall : 0.0

## Dummy baseline
- The dummy (most_frequent) always predicts majority class for every session.
- Accuracy = 84.4% because 84.4% of sessions are non-buyers, so "always no" is right that often.
- Recall = 0.0% because it never predicts minority class, so it catches none of the real buyers.
- Conclusion: accuracy is misleading on imbalanced data; we use PR-AUC instead.

## Logistic regression pipeline

In [13]:
X_train.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000,9764.000000
mean,2.342687,82.219938,0.510344,34.950623,32.101803,1207.264687,0.020296,0.041469,5.945606,0.062351,2.130582,2.371876,3.134986,4.059402
std,3.349268,179.502363,1.282728,143.828323,44.817312,1926.389159,0.045234,0.046145,18.860076,0.199959,0.909649,1.734820,2.389418,4.026181
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,8.000000,193.466667,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,9.000000,0.000000,0.000000,18.000000,617.000000,0.002857,0.025000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,94.725000,0.000000,0.000000,39.000000,1483.650000,0.016667,0.049242,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [14]:
numeric_cols = ['Administrative', 'Administrative_Duration','Informational','Informational_Duration','ProductRelated','ProductRelated_Duration','BounceRates','ExitRates','PageValues','SpecialDay']
categorical_cols = ['OperatingSystems','Browser','Region','TrafficType','Weekend','Month','VisitorType']
len(numeric_cols + categorical_cols)

17

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [16]:
preprocessor = ColumnTransformer([("num",StandardScaler(),numeric_cols),("category",OneHotEncoder(handle_unknown= 'ignore', sparse_output=False),categorical_cols)])

In [17]:
logreg_pipe = Pipeline([("prep", preprocessor), ("lr_model", LogisticRegression())])

In [18]:
logreg_pipe.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Administrative',
                                                   'Administrative_Duration',
                                                   'Informational',
                                                   'Informational_Duration',
                                                   'ProductRelated',
                                                   'ProductRelated_Duration',
                                                   'BounceRates', 'ExitRates',
                                                   'PageValues',
                                                   'SpecialDay']),
                                                 ('category',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['OperatingSystems',
                                                   'Browser', 'Region',
                                                   'TrafficType', 'Weekend',
                                                   'Month', 'VisitorType'])])),
                ('lr_model', LogisticRegression())])

In [19]:
logreg_pipe.predict_proba(X_train.head())

array([[0.17766248, 0.82233752],
       [0.42140132, 0.57859868],
       [0.94732716, 0.05267284],
       [0.92838859, 0.07161141],
       [0.95462574, 0.04537426]])

In [20]:
y_train.head()

7556      True
11924     True
3306     False
207      False
4460     False
Name: Revenue, dtype: bool

In [21]:
logreg_pipe.classes_

array([False,  True])

## Logistic regression summary
- Structure: 10 numeric columns are scaled with mean and std, 7 categorical columns are one-hot encoded with 64 features. In total 74 features going into model.
- Unknown categories are ignored (`handle_unknown='ignore'`). Example: TrafficType 12 (1 session) is absent from train.
- Fitted on the training set only.
- `predict_proba` returns 2 columns in the order of `classes_` = [False, True]: column 0 = No purchase, column 1 = Purchase. Each row sums to 1.
- We use column 1 for PR-AUC, because PR-AUC measures how well the model ranks the positive class at the top.
- Sanity check on 5 training rows.

In [22]:
from sklearn.model_selection import StratifiedKFold, cross_validate

cv = StratifiedKFold(n_splits= 5, shuffle= True, random_state= 42)

In [23]:
lr_cv = cross_validate(logreg_pipe, X_train, y_train, cv = cv, scoring= "average_precision")
lr_cv

{'fit_time': array([0.04637074, 0.02464485, 0.03265929, 0.03914785, 0.02996898]),
 'score_time': array([0.00459003, 0.00389814, 0.00392199, 0.00616479, 0.00555706]),
 'test_score': array([0.650092  , 0.59438053, 0.63246486, 0.64764865, 0.65318198])}

In [24]:
print(f" logistic regression + cross validation: \n mean: {lr_cv["test_score"].mean():.3f} \n standard deviation : {lr_cv['test_score'].std():.3f}")

 logistic regression + cross validation:
 mean: 0.636
 standard deviation : 0.022

In [25]:
dummy_cv = cross_validate(dummy, X_train, y_train, cv = cv, scoring= "average_precision")
print(dummy_cv['test_score'].mean())
print(dummy_cv['test_score'].std())

0.1562884024577573
0.00019923684608644864

In [26]:
rows = [{'model' : 'Dummy (most frequent)', 'pr_auc_mean' : dummy_cv['test_score'].mean().round(3), 'pr_auc_std':dummy_cv['test_score'].std().round(3)},
        {'model' : 'Logistic Regression', 'pr_auc_mean' : lr_cv["test_score"].mean().round(3), 'pr_auc_std':lr_cv['test_score'].std().round(3)}]

In [27]:
comparison_table = pd.DataFrame(rows)

In [28]:
comparison_table

                   model  pr_auc_mean  pr_auc_std
0  Dummy (most frequent)        0.156       0.000
1    Logistic Regression        0.636       0.022

## Cross-validation :
- 5-fold stratified CV on the training set, metric = PR-AUC (average precision)
- Logistic regression 0.636 ± 0.022, x4 better than dummy (0.156)

===================================================================================

## Gradient Boosting

In [29]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [30]:
hgb_pipe = Pipeline([("prep", preprocessor), ("hgb_model", HistGradientBoostingClassifier(random_state= 42))])

In [31]:
hgb_cv = cross_validate(hgb_pipe, X_train, y_train, cv = cv, scoring= "average_precision")

In [32]:
print(hgb_cv['test_score'].mean())
print(hgb_cv['test_score'].std())

0.7423994655620276
0.022444269839407883

In [33]:
rows.append({'model' : 'Gradient boosting', 'pr_auc_mean' : hgb_cv['test_score'].mean().round(3), 'pr_auc_std':hgb_cv['test_score'].std().round(3)})

In [34]:
comparison_table = pd.DataFrame(rows)
comparison_table

                   model  pr_auc_mean  pr_auc_std
0  Dummy (most frequent)        0.156       0.000
1    Logistic Regression        0.636       0.022
2      Gradient boosting        0.742       0.022

## Gradient boosting:
- Same preprocessing and CV folds; only the model changed (HistGradientBoostingClassifier, defaults).
- PR-AUC 0.742 ± 0.022

## Tuning (gradient boosting)

In [35]:
from sklearn.model_selection import GridSearchCV

In [37]:
hgb_pipe['hgb_model']

HistGradientBoostingClassifier(random_state=42)

In [38]:
grid_params = {
    "hgb_model__learning_rate" : [0.05, 0.1, 0.2],
    "hgb_model__max_leaf_nodes" : [21, 31, 41],
    "hgb_model__min_samples_leaf" : [10, 20, 30]
}

In [39]:
grid_search = GridSearchCV(hgb_pipe, grid_params, cv = cv, scoring= 'average_precision')

In [40]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('prep',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['Administrative',
                                                                          'Administrative_Duration',
                                                                          'Informational',
                                                                          'Informational_Duration',
                                                                          'ProductRelated',
                                                                          'ProductRelated_Duration',
                                                                          'BounceRates',
                                                                          'ExitRates',
                                                                          'PageValues',
                                                                          'SpecialDay']),
                                                                        ('cat...
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['OperatingSystems',
                                                                          'Browser',
                                                                          'Region',
                                                                          'TrafficType',
                                                                          'Weekend',
                                                                          'Month',
                                                                          'VisitorType'])])),
                                       ('hgb_model',
                                        HistGradientBoostingClassifier(random_state=42))]),
             param_grid={'hgb_model__learning_rate': [0.05, 0.1, 0.2],
                         'hgb_model__max_leaf_nodes': [21, 31, 41],
                         'hgb_model__min_samples_leaf': [10, 20, 30]},
             scoring='average_precision')

In [41]:
grid_search.best_params_

{'hgb_model__learning_rate': 0.05,
 'hgb_model__max_leaf_nodes': 21,
 'hgb_model__min_samples_leaf': 20}

In [42]:
grid_search.best_score_

np.float64(0.7568666958555393)

## results:
it increased the score from 0.742 to 0.757 with params of (learning rate = 0.05,
max_leaf_nodes = 21, min_samples_leaf = 20), which is smaller than CV spread 
(±0.022), it's small improvement and could partly be noise.